version: '3.3'

services:
  db:
    container_name: bookdb
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: book
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - 7432:5432

